server:
  port: 8090

spring:
  datasource:
    url: <placeholder>
    username: <placeholder>
    password: <placeholder>
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true